import { describe, it, expect } from "vitest";
import { checkYtdlp, listSubtitles, downloadSubtitle } from "../src/ytdlp.js";

// These tests require yt-dlp to be installed and network access.
// They use a known CC-licensed video with subtitles.
// Skipped in CI via the CI environment variable.

const TEST_URL = "https://www.youtube.com/watch?v=jNQXAC9IVRw"; // "Me at the zoo" - first YouTube video

describe.skipIf(!!process.env.CI)("yt-dlp wrapper", () => {
  it("checkYtdlp succeeds when yt-dlp is installed", async () => {
    await expect(checkYtdlp()).resolves.toBeUndefined();
  }, 10_000);

  it("listSubtitles returns metadata and tracks for a known video", async () => {
    const { metadata, tracks } = await listSubtitles(TEST_URL);

    expect(metadata.title).toBe("Me at the zoo");
    expect(metadata.channel).toBeTruthy();
    expect(metadata.url).toContain("youtube.com");

    expect(tracks.length).toBeGreaterThan(0);
    for (const track of tracks) {
      expect(track).toHaveProperty("language");
      expect(track).toHaveProperty("isAutoGenerated");
      expect(track).toHaveProperty("formats");
    }
  }, 30_000);

  it("downloadSubtitle returns metadata and VTT content", async () => {
    const { metadata, vtt } = await downloadSubtitle(TEST_URL, "en");

    expect(metadata.title).toBe("Me at the zoo");
    expect(vtt).toContain("WEBVTT");
    expect(vtt).toContain("-->");
  }, 30_000);
});
