import { describe, it, expect } from "vitest";
import { checkYtdlp, listSubtitles, downloadSubtitle } from "../src/ytdlp.js";

// These tests require yt-dlp to be installed and network access.
// They use a known CC-licensed video with subtitles.
// Skip with: npx vitest run --testPathIgnorePatterns ytdlp

const TEST_URL = "https://www.youtube.com/watch?v=jNQXAC9IVRw"; // "Me at the zoo" - first YouTube video

describe("yt-dlp wrapper", () => {
  it("checkYtdlp succeeds when yt-dlp is installed", async () => {
    await expect(checkYtdlp()).resolves.toBeUndefined();
  }, 10_000);

  it("listSubtitles returns tracks for a known video", async () => {
    const tracks = await listSubtitles(TEST_URL);
    expect(tracks.length).toBeGreaterThan(0);

    for (const track of tracks) {
      expect(track).toHaveProperty("language");
      expect(track).toHaveProperty("isAutoGenerated");
      expect(track).toHaveProperty("formats");
    }
  }, 30_000);

  it("downloadSubtitle returns VTT content", async () => {
    const vtt = await downloadSubtitle(TEST_URL, "en");
    expect(vtt).toContain("WEBVTT");
    expect(vtt).toContain("-->");
  }, 30_000);
});
