import { execFile } from "node:child_process";
import { mkdtemp, readdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import type { SubtitleTrack } from "./types.js";

const execFileAsync = promisify(execFile);
const TIMEOUT_MS = 30_000;

/**
 * Verify yt-dlp is available in PATH.
 */
export async function checkYtdlp(): Promise<void> {
  try {
    await execFileAsync("yt-dlp", ["--version"], { timeout: 5000 });
  } catch {
    throw new Error(
      "yt-dlp is not installed or not in PATH. Install it from https://github.com/yt-dlp/yt-dlp"
    );
  }
}

/**
 * List available subtitle tracks for a video URL.
 * Uses --dump-json to get structured metadata including subtitle info.
 */
export async function listSubtitles(url: string): Promise<SubtitleTrack[]> {
  await checkYtdlp();

  const { stdout } = await execFileAsync(
    "yt-dlp",
    ["--dump-json", "--skip-download", url],
    { timeout: TIMEOUT_MS, maxBuffer: 10 * 1024 * 1024 }
  );

  const info = JSON.parse(stdout);
  const tracks: SubtitleTrack[] = [];

  // Manual subtitles
  if (info.subtitles) {
    for (const [lang, entries] of Object.entries<any[]>(info.subtitles)) {
      if (!entries?.length) continue;
      tracks.push({
        language: lang,
        name: entries[0]?.name || lang,
        isAutoGenerated: false,
        formats: entries.map((e: any) => e.ext).filter(Boolean),
      });
    }
  }

  // Auto-generated subtitles
  if (info.automatic_captions) {
    for (const [lang, entries] of Object.entries<any[]>(
      info.automatic_captions
    )) {
      if (!entries?.length) continue;
      tracks.push({
        language: lang,
        name: entries[0]?.name || lang,
        isAutoGenerated: true,
        formats: entries.map((e: any) => e.ext).filter(Boolean),
      });
    }
  }

  return tracks;
}

/**
 * Download a subtitle track and return its VTT content.
 *
 * If no language is specified, prefers manual English subs,
 * falls back to auto-generated English, then any available track.
 */
export async function downloadSubtitle(
  url: string,
  language?: string
): Promise<string> {
  await checkYtdlp();

  const tmp = await mkdtemp(join(tmpdir(), "yt-dlp-mcp-"));

  try {
    const args = ["--skip-download", "--sub-format", "vtt", "-o", join(tmp, "sub")];

    if (language) {
      args.push("--write-subs", "--sub-lang", language);
    } else {
      // Write both manual and auto subs; yt-dlp prefers manual when both exist
      args.push("--write-subs", "--write-auto-subs", "--sub-lang", "en");
    }

    args.push(url);

    await execFileAsync("yt-dlp", args, { timeout: TIMEOUT_MS });

    // Find the downloaded .vtt file
    const files = await readdir(tmp);
    const vttFile = files.find((f) => f.endsWith(".vtt"));

    if (!vttFile) {
      const lang = language || "en";
      throw new Error(
        `No subtitle track found for language "${lang}". Use list_subtitles to see available tracks.`
      );
    }

    return await readFile(join(tmp, vttFile), "utf-8");
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
}
