import { execFile } from "node:child_process";
import { mkdtemp, readdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import type { SubtitleTrack, VideoComment, VideoMetadata } from "./types.js";

const execFileAsync = promisify(execFile);
const TIMEOUT_MS = 30_000;

/**
 * Verify yt-dlp is available in PATH.
 */
export async function checkYtdlp(): Promise<void> {
  try {
    await execFileAsync("yt-dlp", ["--version"], { timeout: 5000 });
  } catch {
    throw new Error(
      "yt-dlp is not installed or not in PATH. Install it from https://github.com/yt-dlp/yt-dlp"
    );
  }
}

/**
 * Fetch video JSON metadata via --dump-json.
 */
async function fetchVideoJson(url: string): Promise<any> {
  await checkYtdlp();

  const { stdout } = await execFileAsync(
    "yt-dlp",
    ["--dump-json", "--skip-download", url],
    { timeout: TIMEOUT_MS, maxBuffer: 10 * 1024 * 1024 }
  );

  return JSON.parse(stdout);
}

/**
 * Extract VideoMetadata from yt-dlp JSON output.
 */
function extractMetadata(info: any): VideoMetadata {
  return {
    title: info.title ?? "",
    description: info.description ?? "",
    channel: info.channel ?? info.uploader ?? "",
    channelUrl: info.channel_url ?? "",
    uploadDate: info.upload_date ?? "",
    duration: info.duration ?? 0,
    durationString: info.duration_string ?? "",
    viewCount: info.view_count ?? null,
    likeCount: info.like_count ?? null,
    commentCount: info.comment_count ?? null,
    categories: info.categories ?? [],
    tags: info.tags ?? [],
    thumbnail: info.thumbnail ?? "",
    url: info.webpage_url ?? "",
  };
}

/**
 * Extract subtitle tracks from yt-dlp JSON output.
 */
function extractSubtitleTracks(info: any): SubtitleTrack[] {
  const tracks: SubtitleTrack[] = [];

  if (info.subtitles) {
    for (const [lang, entries] of Object.entries<any[]>(info.subtitles)) {
      if (!entries?.length) continue;
      tracks.push({
        language: lang,
        name: entries[0]?.name || lang,
        isAutoGenerated: false,
        formats: entries.map((e: any) => e.ext).filter(Boolean),
      });
    }
  }

  if (info.automatic_captions) {
    for (const [lang, entries] of Object.entries<any[]>(
      info.automatic_captions
    )) {
      if (!entries?.length) continue;
      tracks.push({
        language: lang,
        name: entries[0]?.name || lang,
        isAutoGenerated: true,
        formats: entries.map((e: any) => e.ext).filter(Boolean),
      });
    }
  }

  return tracks;
}

/**
 * Get video metadata.
 */
export async function getVideoMetadata(url: string): Promise<VideoMetadata> {
  const info = await fetchVideoJson(url);
  return extractMetadata(info);
}

/**
 * List available subtitle tracks for a video URL.
 * Also returns video metadata since we fetch it in the same call.
 */
export async function listSubtitles(
  url: string
): Promise<{ metadata: VideoMetadata; tracks: SubtitleTrack[] }> {
  const info = await fetchVideoJson(url);
  return {
    metadata: extractMetadata(info),
    tracks: extractSubtitleTracks(info),
  };
}

/**
 * Download a subtitle track and return its VTT content,
 * along with video metadata.
 *
 * If no language is specified, prefers manual English subs,
 * falls back to auto-generated English, then any available track.
 */
export async function downloadSubtitle(
  url: string,
  language?: string
): Promise<{ metadata: VideoMetadata; vtt: string }> {
  const [info, vtt] = await Promise.all([
    fetchVideoJson(url),
    downloadVtt(url, language),
  ]);

  return { metadata: extractMetadata(info), vtt };
}

/**
 * Download a subtitle track and return raw VTT content.
 */
async function downloadVtt(
  url: string,
  language?: string
): Promise<string> {
  await checkYtdlp();

  const tmp = await mkdtemp(join(tmpdir(), "yt-dlp-mcp-"));

  try {
    const args = ["--skip-download", "--sub-format", "vtt", "-o", join(tmp, "sub")];

    if (language) {
      args.push("--write-subs", "--sub-lang", language);
    } else {
      // Write both manual and auto subs; yt-dlp prefers manual when both exist
      args.push("--write-subs", "--write-auto-subs", "--sub-lang", "en");
    }

    args.push(url);

    await execFileAsync("yt-dlp", args, { timeout: TIMEOUT_MS });

    // Find the downloaded .vtt file
    const files = await readdir(tmp);
    const vttFile = files.find((f) => f.endsWith(".vtt"));

    if (!vttFile) {
      const lang = language || "en";
      throw new Error(
        `No subtitle track found for language "${lang}". Use list_subtitles to see available tracks.`
      );
    }

    return await readFile(join(tmp, vttFile), "utf-8");
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
}
